name: intl_translation
version: 0.17.10+2
author: Dart Team <misc@dartlang.org>
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/dart-lang/intl_translation
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  args: '^2.1.0'
  dart_style: ^2.0.0
  intl: '^0.17.0'
  path: ^1.8.0
  petitparser: ^4.1.0
dev_dependencies:
  test: ^1.17.1
